version: "3.2"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
       - 5755:5755/udp
       - 6831:6831/udp
       - 6832:6832/udp
       - 5778:5778
       - 16686:16686
       - 14268:14268

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: